/*
 * generated by Xtext 2.22.0
 */
package fr.cs.info.sl.microc.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class MicroCProposalProvider extends AbstractMicroCProposalProvider {
}
