/*
 * generated by Xtext 2.22.0
 */
package fr.cs.info.sl.microc;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class MicroCStandaloneSetup extends MicroCStandaloneSetupGenerated {

	public static void doSetup() {
		new MicroCStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
