/*
 * generated by Xtext 2.22.0
 */
package fr.cs.info.sl.microc.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class MicroCUiModule extends AbstractMicroCUiModule {

	public MicroCUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
