/*
 * generated by Xtext 2.22.0
 */
package fr.cs.info.sl.microc.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.cs.info.sl.microc.MicroCRuntimeModule;
import fr.cs.info.sl.microc.MicroCStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class MicroCIdeSetup extends MicroCStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MicroCRuntimeModule(), new MicroCIdeModule()));
	}
	
}
